import { navmenu } from "./navmenu";
import { controlmusic } from "./controlmusic";
import { header } from "./header";
import { personal } from "./personal";
import { loadData } from "./loadData";
navmenu.start();
header.start();
personal.start();
loadData.start();
controlmusic.start();
